/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.innovaciones.reporte.util;

/**
 *
 * @author pisama
 */
public enum Enums {

    PREVENTIVO("MANTENIMIENTO PREVENTIVO", "PREVENTIVO"),
    CORRECTIVO("MANTENIMIENTO CORRECTIVO", "CORRECTIVO"),
    MANTENIMIENTO_PROCESAMIENTO("MANTENIMIENTO PROCESAMIENTO", "PROCESAMIENTO"),
    MANTENIMIENTO_PREVENTIVO_IMAGEN("MANTENIMIENTO PREVENTIVO IMAGEN", "IMAGEN_PREVENTIVO"),
    MANTENIMIENTO_PREVENTIVO_FIJACION("MANTENIMIENTO PREVENTIVO FIJACION", "FIJACION_PREVENTIVO"),
    MANTENIMIENTO_EXTERIORES("MANTENIMIENTO EXTERIORES", "EXTERIORES"),
    MANTENIMIENTO_SUMINISTROS("MANTENIMIENTO SUMINISTROS", "SUMINISTROS"),
    MANTENIMIENTO_CORRECTIVO_IMAGEN("MANTENIMIENTO CORRECTIVO IMAGEN", "IMAGEN_CORRECTIVO"),
    MANTENIMIENTO_CORRECTIVO_FIJACION("MANTENIMIENTO CORRECTIVO FIJACION", "FIJACION_CORRECTIVO"),
    MANTENIMIENTO_CORRECTIVO_REVELADO("MANTENIMIENTO CORRECTIVO REVELADO", "REVELADO"),
    MANTENIMIENTO_ALIMENTACION("TIPO MANTENIMIENTO ALIMENTACION", "ALIMENTACION"),
    MANTENIMIENTO_OTROS("MANTENIMIENTO OTROS", "OTROS"),
    TIPO_REPORTE_DIAGNOSTICO("REPORTE DIAGNOSTICO", "DIAGNOSTICO"),
    TIPO_REPORTE_REPARACION("REPORTE REPARACION", "REPARACION"),
    TIPO_REPORTE_CONTADORES("REPORTE CONTADORES", "CONTADOR"),
    PARAMETRO_TIPO_REPORTE("PARAMETRO TIPO REPORTE", "TIPO_REPORTE"),
    ESTADO_REPORTE_PROCESO("ESTADO DE REPORTE EN PROCESO", "PROCESANDO"),
    ESTADO_REPORTE_FINALIADO("ESTADO DE REPORTE FINALIZADO", "FINALIZADO"),
    ROLE_ADMIN("ROLE ADMINISTRADOR", "ROLE_ADMIN"),
    ROLE_TECNICO("ROLE TECNICO", "ROLE_TECNICO"),
    ROLE_VENTAS("ROLE VENTAS", "ROLE_VENTAS"),
    ROLE_POSTVENTAS("ROLE POSTVENTAS", "ROLE_POSTVENTAS"),
    PARAMETRO_ID_REPORTE("PARAMETRO ID REPORTE", "ID REPORTE"),
    PARAMETRO_MENSAJE_LOGIN("PARAMETRO MENSAJE LOGIN", "MENSAJE LOGIN"),
    ASIGNACION("ASIGNACION", "ASIGNACION"),
    REPORTE("REPORTE", "REPORTE"),
    INSTALACION("INSTALACION", "INSTALACION"),
    ESTADO_ASIGNACION_ASIGNADO("ASIGNADO", "ASIGNADO"),
    ESTADO_ASIGNACION_ELIMINADO("ELIMINADO", "ELIMINADO"),
    PAGINA_REPORTE("PAGINA REPORTE", "/reportes/paginas/reporte.jsf"),
    PAGINA_REPORTE_NUEVA_INSTALACION("PAGINA REPORTE", "/reportes/paginas/instalaciones/instalacion-nueva.jsf"),
    TIPO_INSTALACION("TIPO INSTALACION", "TIPO_INSTALACION"),
    INSTALACION_NUEVA("INSTALACION NUEVA", "NUEVA"),
    INSTALACION_TEMPORAL("INSTALACION TEMPORAL", "TEMPORAL"),
    INSTALACION_MEDICIONES("INSTALACION MEDICIONES", "MEDICIONES"),
    INSTALACION_CONSIDERACIONES("INSTALACION CONSDIREACIONES", "CONSIDERACIONES"),
    INSTALACION_PREGUNTAS("INSTALACION PREGUNTAS", "PREGUNTAS"),
    CODIGO_EMPRESA("CODIGO EMPRESA", "CODE_ENTERPRISE"),
    DATOS_REEMPLAZO("DATOS A REEMPLAZAR", "DATOS_REEMPLAZO"),
    DATOS_TEMPORAL("DATOS TEMPORALES", "DATOS_TEMPORAL");

    private final String propertyName; //Nombre del estado (propiedad)
    private final String value; // Valor del estado

    Enums(String propertyName, String value) {
        this.propertyName = propertyName;
        this.value = value;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public String getValue() {
        return value;
    }
}
